name: 'Publish Game'
description: 'Publish a WebGL game to Final Parsec.'
inputs:
  game-name:
    description: 'The name of the game to publish'
    required: true
    default: 'Untitled Game'
  asset-directory:
    description: 'The directory containing assets to be published'
    required: true
    default: '/fp-publish'
outputs:
  time:
    description: 'The time the game was published'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
